fix(bootstrap): create app user with uid 1000
The UCS base image/python update caused ansible to no longer
ignore the missing user (1000) in the container:

Traceback (most recent call last):
  File "/usr/lib/python3.13/getpass.py", line 173, in getuser
    return pwd.getpwuid(os.getuid())[0]
           ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'getpwuid(): uid not found: 1000'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/cli/__init__.py", line 92, in <module>
    from ansible.utils.display import Display
  File "/usr/lib/python3/dist-packages/ansible/utils/display.py", line 172, in <module>
    class FilterUserInjector(logging.Filter):
    ...<13 lines>...
            return True
  File "/usr/lib/python3/dist-packages/ansible/utils/display.py", line 179, in FilterUserInjector
    username = getpass.getuser()
  File "/usr/lib/python3.13/getpass.py", line 175, in getuser
    raise OSError('No username set in the environment') from e
OSError: No username set in the environment

Fixed by creating the app user in the container.

univention/dev/projects/keycloak/keycloak-app#273